# Generated by Django 5.2.14 on 2026-05-14 17:11

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def _ensure_pgvector_extension(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_extracted_text"),
    ]

    operations = [
        migrations.RunPython(_ensure_pgvector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Chunk order within the document (0-based)."
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "documents_documentchunk",
                "ordering": ("document_id", "position"),
            },
        ),
    ]
