# Generated by Django 5.2.14 on 2026-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("waiting_approval", "Waiting approval"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
    ]
