# Generated by Django 5.2.14 on 2026-05-15 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_approval_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("waiting_compliance", "Waiting compliance"),
                    ("waiting_approval", "Waiting approval"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("resource_type", models.CharField(db_index=True, max_length=64)),
                ("resource_id", models.CharField(db_index=True, max_length=64)),
                ("before_json", models.JSONField(blank=True, null=True)),
                ("after_json", models.JSONField(blank=True, null=True)),
                ("token_usage", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflows_auditlog",
                "ordering": ("-id",),
            },
        ),
    ]
